### ISSUE TITLE
日志等级配置无效

### ISSUE THREAD

**Issue by errnull** [yusangeng/chivy#1]
在项目里面使用了日志配置：
<img width="848" alt="屏幕快照2019-09-18下午6 31 36" src="https://user-images.githubusercontent.com/28481578/65141118-9096a800-da42-11e9-9888-2bd3ecab330d.png">

打印相关日志：
<img width="630" alt="屏幕快照2019-09-18下午6 32 08" src="https://user-images.githubusercontent.com/28481578/65141152-a2784b00-da42-11e9-8343-c4c361b28251.png">

出来的结果：
![屏幕快照2019-09-18下午6 32 26](https://user-images.githubusercontent.com/28481578/65141184-adcb7680-da42-11e9-99dc-bf1f6944426b.png)
麻烦大佬看一下。

**Comment by yusangeng** [comment]
Ok, 我正在检查。

**Comment by yusangeng** [comment]
我看了一下你的代码，配置信息是需要先于Logger存在的。

比如你可以在html或者konph库被加载之前，设置window.__Konph的值。因为这个是“初始化数据”，初始化之后，就不会再读取了。

**Comment by errnull** [comment]
你好，我修正了代码，还是没有对应输出。
我这里新建了一个 Demo，
<img width="724" alt="屏幕快照2019-09-23上午10 27 00" src="https://user-images.githubusercontent.com/28481578/65398967-b9c18a80-ddec-11e9-94f8-1b9bfa9028ad.png">
![屏幕快照2019-09-23上午10 27 06](https://user-images.githubusercontent.com/28481578/65398969-bb8b4e00-ddec-11e9-8d35-6023be5490bd.png)
https://github.com/errnullDebuger/ChivyDemo
麻烦大佬看一下。
@yusangeng

**Comment by errnull** [comment]
多谢指正
